# Generated by Django 5.2.13 on 2026-04-30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PreferenceContext",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("user_id", models.BigIntegerField(db_index=True)),
                ("source", models.CharField(default="signup", max_length=30)),
                ("content", models.TextField()),
                ("semantic_vec", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "vector_preference_contexts",
            },
        ),
        migrations.CreateModel(
            name="SteeringVector",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("context_id", models.UUIDField(db_index=True)),
                ("user_id", models.BigIntegerField(db_index=True)),
                ("layer", models.IntegerField(default=0)),
                ("steering_vec", models.JSONField(blank=True, default=list)),
                ("norm", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "vector_steering_vectors",
            },
        ),
        migrations.AddIndex(
            model_name="preferencecontext",
            index=models.Index(fields=["user_id", "created_at"], name="vector_pref_user_id_2d231e_idx"),
        ),
        migrations.AddIndex(
            model_name="steeringvector",
            index=models.Index(fields=["user_id", "context_id", "layer"], name="vector_steer_user_id_35c46a_idx"),
        ),
    ]

