# Generated by Django 5.2.13 on 2026-04-30

from django.db import migrations


def enable_pgvector(apps, schema_editor):
    """
    Optional pgvector enablement.
    - Safe on Postgres with pgvector installed.
    - No-op on Postgres without pgvector (keeps JSONField-based schema working).
    """
    if schema_editor.connection.vendor != "postgresql":
        return
    try:
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("CREATE EXTENSION IF NOT EXISTS vector")
    except Exception:
        # pgvector not installed on the server; keep running without it.
        return


class Migration(migrations.Migration):
    dependencies = [
        ("vectors", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(enable_pgvector, reverse_code=migrations.RunPython.noop),
    ]

