# Generated by Django 5.2.13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vectors", "0002_enable_pgvector_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="preferencecontext",
            name="representation_meta",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
