# Generated by Django 6.0.5 on 2026-05-26 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vectors', '0004_alter_semantic_vec_to_vector'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='preferencecontext',
            new_name='vector_pref_user_id_96ac85_idx',
            old_name='vector_pref_user_id_2d231e_idx',
        ),
        migrations.RenameIndex(
            model_name='steeringvector',
            new_name='vector_stee_user_id_eb0593_idx',
            old_name='vector_steer_user_id_35c46a_idx',
        ),
    ]
