# Generated by Django 5.2.13 on 2026-06-25 03:17

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vectors', '0005_rename_vector_pref_user_id_2d231e_idx_vector_pref_user_id_96ac85_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencecontext',
            name='semantic_vec',
            field=pgvector.django.vector.VectorField(dimensions=384, null=True),
        ),
    ]
