# Generated by Django 6.0.5 on 2026-05-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_appointment_visit_summary_cache'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recording',
            name='audio_content_type',
        ),
        migrations.RemoveField(
            model_name='recording',
            name='audio_object_key',
        ),
        migrations.RemoveField(
            model_name='recording',
            name='audio_sha256',
        ),
        migrations.RemoveField(
            model_name='recording',
            name='audio_size_bytes',
        ),
        migrations.RemoveField(
            model_name='recording',
            name='audio_storage',
        ),
        migrations.RemoveField(
            model_name='recording',
            name='extracted_entities',
        ),
        migrations.RemoveField(
            model_name='recording',
            name='status',
        ),
        migrations.RemoveField(
            model_name='recording',
            name='transcript_json',
        ),
        migrations.RemoveField(
            model_name='recording',
            name='transcript_text',
        ),
        migrations.AddField(
            model_name='recording',
            name='audio_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
