# Generated by Django 5.2.13 on 2026-06-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_personalizationprofile_ml_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='audio_content_type',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='recording',
            name='audio_object_key',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='recording',
            name='audio_sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='recording',
            name='audio_size_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recording',
            name='audio_storage',
            field=models.CharField(choices=[('local', 'local'), ('s3', 's3'), ('inline', 'inline')], default='local', max_length=20),
        ),
        migrations.AddField(
            model_name='recording',
            name='extracted_entities',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='recording',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('uploaded', 'uploaded'), ('transcribing', 'transcribing'), ('transcribed', 'transcribed'), ('extracting', 'extracting'), ('extracted', 'extracted'), ('failed', 'failed')], default='created', help_text='created|uploaded|transcribing|transcribed|extracting|extracted|failed', max_length=30),
        ),
        migrations.AddField(
            model_name='recording',
            name='transcript_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='recording',
            name='transcript_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
