# Generated by Django 5.2.13 on 2026-07-21 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_personalizationprofile_profile_basics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recording',
            name='audio_storage',
        ),
    ]
