# Generated by Django 5.2.13 on 2026-04-30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Medication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("rxnorm_code", models.CharField(blank=True, default="", max_length=50)),
                ("dose", models.CharField(blank=True, default="", max_length=120)),
                ("frequency", models.CharField(blank=True, default="", max_length=120)),
                ("route", models.CharField(blank=True, default="", max_length=80)),
                ("start_date", models.CharField(blank=True, default="", max_length=10)),
                ("end_date", models.CharField(blank=True, default="", max_length=10)),
                ("status", models.CharField(choices=[("active", "Active"), ("modified", "Modified"), ("discontinued", "Discontinued")], default="active", max_length=20)),
                ("source", models.CharField(default="manual", max_length=30)),
                ("verification", models.CharField(default="unverified", max_length=30)),
                ("confidence", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="medications", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "medications", "ordering": ["-updated_at"]},
        ),
        migrations.CreateModel(
            name="MedicationReminder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("time_of_day", models.CharField(max_length=5)),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                ("days_of_week", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("medication", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reminders", to="medications.medication")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="medication_reminders", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "medication_reminders", "ordering": ["time_of_day"]},
        ),
        migrations.CreateModel(
            name="MedicationEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(choices=[("created", "Created"), ("modified", "Modified"), ("discontinued", "Discontinued"), ("verified", "Verified")], max_length=20)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                ("medication", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="events", to="medications.medication")),
            ],
            options={"db_table": "medication_events", "ordering": ["-occurred_at"]},
        ),
    ]

