# Generated by Django 5.2.13 on 2026-04-30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExportedPdf",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.BigIntegerField(db_index=True)),
                ("appointment_id", models.BigIntegerField(db_index=True)),
                ("filename", models.CharField(max_length=255)),
                ("s3_bucket", models.CharField(blank=True, default="", max_length=255)),
                ("s3_key", models.CharField(blank=True, default="", max_length=1024)),
                ("storage", models.CharField(default="local", max_length=20)),
                ("sha256", models.CharField(blank=True, default="", max_length=64)),
                ("size_bytes", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"db_table": "exported_pdfs", "ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="exportedpdf",
            index=models.Index(fields=["user_id", "appointment_id", "created_at"], name="exported_pd_user_id_4acdfd_idx"),
        ),
    ]

