# Generated by Django 6.0.5 on 2026-05-26 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='exportedpdf',
            new_name='exported_pd_user_id_2bc34d_idx',
            old_name='exported_pd_user_id_4acdfd_idx',
        ),
    ]
