# Generated by Django 5.2.13 on 2026-07-21 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_exportedpdf_user_exportedpdf_appointment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportedpdf',
            name='s3_bucket',
        ),
        migrations.RemoveField(
            model_name='exportedpdf',
            name='s3_key',
        ),
        migrations.RemoveField(
            model_name='exportedpdf',
            name='storage',
        ),
    ]
