# Generated by Django 6.0.5 on 2026-05-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_pushdevice_notification_prefs'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pushdevice',
            new_name='push_device_user_id_8c34d3_idx',
            old_name='push_devices_user_active_idx',
        ),
        migrations.AlterField(
            model_name='pushdevice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
